services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nest-app
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
