# Stage 1: Build
FROM node:alpine AS build

# Install PostgreSQL client for application use
RUN apk add --no-cache postgresql-client

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies using npm ci
RUN npm install

# Copy the rest of the application files
COPY . .

# Build the application
RUN npm run build

# Set the working directory inside the container
WORKDIR /usr/src/app

# Expose the application port
EXPOSE 3000

# Command to run the application
CMD ["npm", "run", "start:dev"]
